#!/usr/bin/env python3
"""
Generate machines/search-index.js
Reads every machines/<folder>/index.html, strips HTML tags,
and outputs a JS file with pre-indexed plain text for full-text search.

Run:  python3 generate_search_index.py
"""

import os
import re
import json

MACHINES_DIR = os.path.join(os.path.dirname(__file__), "machines")
OUTPUT_FILE  = os.path.join(MACHINES_DIR, "search-index.js")


def strip_html(html: str) -> str:
    """Remove HTML tags and collapse whitespace."""
    # Remove <script>...</script> blocks
    html = re.sub(r'<script[^>]*>.*?</script>', ' ', html, flags=re.DOTALL | re.IGNORECASE)
    # Remove <style>...</style> blocks
    html = re.sub(r'<style[^>]*>.*?</style>', ' ', html, flags=re.DOTALL | re.IGNORECASE)
    # Remove <nav>...</nav> blocks (navigation, not writeup content)
    html = re.sub(r'<nav[^>]*>.*?</nav>', ' ', html, flags=re.DOTALL | re.IGNORECASE)
    # Remove remaining tags
    html = re.sub(r'<[^>]+>', ' ', html)
    # Decode common HTML entities
    html = html.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>') \
               .replace('&quot;', '"').replace('&#39;', "'").replace('&nbsp;', ' ')
    # Collapse whitespace
    html = re.sub(r'\s+', ' ', html).strip()
    return html


def main():
    entries = []

    for folder in sorted(os.listdir(MACHINES_DIR)):
        html_path = os.path.join(MACHINES_DIR, folder, "index.html")
        if not os.path.isfile(html_path):
            continue

        with open(html_path, "r", encoding="utf-8", errors="ignore") as f:
            raw = f.read()

        text_en = ""
        text_es = ""
        
        # Try to slice out the English and Spanish blocks directly
        if 'id="content-en"' in raw and 'id="content-es"' in raw:
            idx_en = raw.find('id="content-en"')
            idx_es = raw.find('id="content-es"')
            idx_end = raw.find('</article>', idx_es)
            if idx_end == -1:
                idx_end = len(raw)
            
            start_en = raw.rfind('<div', 0, idx_en)
            start_es = raw.rfind('<div', 0, idx_es)
            
            if start_en != -1 and start_es != -1:
                en_html = raw[start_en:start_es]
                es_html = raw[start_es:idx_end]
                text_en = strip_html(en_html)
                text_es = strip_html(es_html)
        
        # Fallback if no specific language blocks found
        if not text_en and not text_es:
            text_en = strip_html(raw)
            text_es = text_en

        entries.append({
            "folder": folder,
            "text": {
                "en": text_en,
                "es": text_es
            }
        })
        print(f"  Indexed: {folder} (EN: {len(text_en):,} chars, ES: {len(text_es):,} chars)")

    # Write JS
    json_data = json.dumps(entries, ensure_ascii=False, indent=None)
    js_content = f"// Auto-generated by generate_search_index.py — do not edit manually\nconst SEARCH_INDEX = {json_data};\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"\nDone! Wrote {len(entries)} entries to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
